Public Class Tanks
    Public Enum Type
        HEAVY
        MEDIUM
        LIGHT
        TD
        SPG
    End Enum
    Public Shared Types As Type() = {Type.HEAVY, Type.MEDIUM, Type.LIGHT, Type.TD, Type.SPG}

    Public Shared Function getTypeNum(ByVal t As Type) As Integer
        Return Array.IndexOf(Types, t)
    End Function

    Private Shared alltanks As List(Of Tank) = Nothing

    Public Shared Function getTank(ByVal name As String) As Tank
        name = name.ToLower()
        For Each t As Tank In getTanks()
            If t.getName().ToLower() = name Then
                Return t
            End If
        Next
        Return Nothing
    End Function

    Public Shared Function getTanks() As List(Of Tank)
        If alltanks Is Nothing Then
            alltanks = New List(Of Tank)
            ' Soviet
            alltanks.Add(New Tank("MS-1", 1, Type.LIGHT))
            alltanks.Add(New Tank("BT-2", 2, Type.LIGHT))
            alltanks.Add(New Tank("T-26", 2, Type.LIGHT))
            alltanks.Add(New Tank("MkVII Tetrarch", 2, Type.LIGHT))
            alltanks.Add(New Tank("BT-7", 3, Type.LIGHT))
            alltanks.Add(New Tank("T-46", 3, Type.LIGHT))
            alltanks.Add(New Tank("BT-SV", 3, Type.LIGHT))
            alltanks.Add(New Tank("M3 Stuart II", 3, Type.LIGHT))
            alltanks.Add(New Tank("T-127", 3, Type.LIGHT))
            alltanks.Add(New Tank("A-20", 4, Type.LIGHT))
            alltanks.Add(New Tank("T-50", 4, Type.LIGHT))
            alltanks.Add(New Tank("Valentine", 4, Type.LIGHT))
            alltanks.Add(New Tank("T-50-2", 5, Type.LIGHT))
            alltanks.Add(New Tank("T-28", 4, Type.MEDIUM))
            alltanks.Add(New Tank("A-32", 4, Type.MEDIUM))
            alltanks.Add(New Tank("T-34", 5, Type.MEDIUM))
            alltanks.Add(New Tank("Matilda", 5, Type.MEDIUM))
            alltanks.Add(New Tank("T-34-85", 6, Type.MEDIUM))
            alltanks.Add(New Tank("T-43", 7, Type.MEDIUM))
            alltanks.Add(New Tank("KV-13", 7, Type.MEDIUM))
            alltanks.Add(New Tank("T-44", 8, Type.MEDIUM))
            alltanks.Add(New Tank("T-54", 9, Type.MEDIUM))
            alltanks.Add(New Tank("KV", 5, Type.HEAVY))
            alltanks.Add(New Tank("KV-220 Beta-Test", 5, Type.HEAVY))
            alltanks.Add(New Tank("Churchill", 5, Type.HEAVY))
            alltanks.Add(New Tank("KV-220", 5, Type.HEAVY))
            alltanks.Add(New Tank("KV-1S", 6, Type.HEAVY))
            alltanks.Add(New Tank("KV-3", 6, Type.HEAVY))
            alltanks.Add(New Tank("IS", 7, Type.HEAVY))
            alltanks.Add(New Tank("IS-3", 8, Type.HEAVY))
            alltanks.Add(New Tank("KV-5", 8, Type.HEAVY))
            alltanks.Add(New Tank("IS-4", 9, Type.HEAVY))
            alltanks.Add(New Tank("IS-7", 10, Type.HEAVY))
            alltanks.Add(New Tank("AT-1", 2, Type.TD))
            alltanks.Add(New Tank("SU-76", 3, Type.TD))
            alltanks.Add(New Tank("SU-85B", 4, Type.TD))
            alltanks.Add(New Tank("SU-85", 5, Type.TD))
            alltanks.Add(New Tank("SU-85I", 5, Type.TD))
            alltanks.Add(New Tank("SU-100", 6, Type.TD))
            alltanks.Add(New Tank("SU-152", 7, Type.TD))
            alltanks.Add(New Tank("ISU-152", 8, Type.TD))
            alltanks.Add(New Tank("Object 704", 9, Type.TD))
            alltanks.Add(New Tank("SU-18", 2, Type.SPG))
            alltanks.Add(New Tank("SU-26", 3, Type.SPG))
            alltanks.Add(New Tank("SU-5", 4, Type.SPG))
            alltanks.Add(New Tank("SU-8", 5, Type.SPG))
            alltanks.Add(New Tank("S-51", 6, Type.SPG))
            alltanks.Add(New Tank("SU-14", 6, Type.SPG))
            alltanks.Add(New Tank("Object 212", 7, Type.SPG))
            alltanks.Add(New Tank("Object 261", 8, Type.SPG))
            ' /Soviet
            ' German
            alltanks.Add(New Tank("Leichttraktor", 1, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw 35 (t)", 2, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw II", 2, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw 38H735 (f)", 2, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw 38 (t)", 3, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw III Ausf. A", 3, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw II Luchs", 3, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw II Ausf. J", 3, Type.LIGHT))
            alltanks.Add(New Tank("T-15", 3, Type.LIGHT))
            alltanks.Add(New Tank("VK 1602 Leopard", 4, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw 38 nA", 4, Type.LIGHT))
            alltanks.Add(New Tank("VK 2801", 5, Type.LIGHT))
            alltanks.Add(New Tank("PzKpfw S35 739 (f)", 3, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw III", 4, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw IV", 5, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw III/IV", 5, Type.MEDIUM))
            alltanks.Add(New Tank("T-25", 5, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw IV Hydraulic", 5, Type.MEDIUM))
            alltanks.Add(New Tank("VK 3601 (H)", 6, Type.MEDIUM))
            alltanks.Add(New Tank("VK 3001 (H)", 6, Type.MEDIUM))
            alltanks.Add(New Tank("VK 3001 (P)", 6, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw V-IV", 6, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw V-IV Alpha", 6, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw V Panther", 7, Type.MEDIUM))
            alltanks.Add(New Tank("VK 3002 (DB)", 7, Type.MEDIUM))
            alltanks.Add(New Tank("Panther II", 8, Type.MEDIUM))
            alltanks.Add(New Tank("E-50", 9, Type.MEDIUM))
            alltanks.Add(New Tank("PzKpfw B2 740 (f)", 4, Type.HEAVY))
            alltanks.Add(New Tank("PzKpfw VI Tiger", 7, Type.HEAVY))
            alltanks.Add(New Tank("PzKpfw VI Tiger (P)", 7, Type.HEAVY))
            alltanks.Add(New Tank("PzKpfw VIB Tiger II", 8, Type.HEAVY))
            alltanks.Add(New Tank("VK 4502 (P) Ausf. A", 8, Type.HEAVY))
            alltanks.Add(New Tank("Löwe", 8, Type.HEAVY))
            alltanks.Add(New Tank("VK 4502 (P) Ausf. B", 9, Type.HEAVY))
            alltanks.Add(New Tank("E-75", 9, Type.HEAVY))
            alltanks.Add(New Tank("Maus", 10, Type.HEAVY))
            alltanks.Add(New Tank("E-100", 10, Type.HEAVY))
            alltanks.Add(New Tank("Panzerjäger I", 2, Type.TD))
            alltanks.Add(New Tank("Marder II", 3, Type.TD))
            alltanks.Add(New Tank("Hetzer", 4, Type.TD))
            alltanks.Add(New Tank("StuG III", 5, Type.TD))
            alltanks.Add(New Tank("JagdPz IV", 6, Type.TD))
            alltanks.Add(New Tank("Jagdpanther", 7, Type.TD))
            alltanks.Add(New Tank("Ferdinand", 8, Type.TD))
            alltanks.Add(New Tank("Jagdtiger", 9, Type.TD))
            alltanks.Add(New Tank("Sturmpanzer I Bison", 2, Type.SPG))
            alltanks.Add(New Tank("Sturmpanzer II", 3, Type.SPG))
            alltanks.Add(New Tank("Wespe", 3, Type.SPG))
            alltanks.Add(New Tank("Grille", 4, Type.SPG))
            alltanks.Add(New Tank("Hummel", 5, Type.SPG))
            alltanks.Add(New Tank("GW Panther", 6, Type.SPG))
            alltanks.Add(New Tank("GW Tiger", 7, Type.SPG))
            alltanks.Add(New Tank("GW Typ E", 8, Type.SPG))
            ' /German
            ' American
            alltanks.Add(New Tank("T1 Cunningham", 1, Type.LIGHT))
            alltanks.Add(New Tank("M2 Light Tank", 2, Type.LIGHT))
            alltanks.Add(New Tank("T2 Light Tank", 2, Type.LIGHT))
            alltanks.Add(New Tank("M3 Stuart", 3, Type.LIGHT))
            alltanks.Add(New Tank("MTLS-1G14", 3, Type.LIGHT))
            alltanks.Add(New Tank("M22 Locust", 3, Type.LIGHT))
            alltanks.Add(New Tank("M5 Stuart", 4, Type.LIGHT))
            alltanks.Add(New Tank("M24 Chaffee", 5, Type.LIGHT))
            alltanks.Add(New Tank("T2 Medium Tank", 2, Type.MEDIUM))
            alltanks.Add(New Tank("M2 Medium Tank", 3, Type.MEDIUM))
            alltanks.Add(New Tank("M3 Lee", 4, Type.MEDIUM))
            alltanks.Add(New Tank("M4 Sherman", 5, Type.MEDIUM))
            alltanks.Add(New Tank("M7", 5, Type.MEDIUM))
            alltanks.Add(New Tank("Ram-II", 5, Type.MEDIUM))
            alltanks.Add(New Tank("M4A2E4", 5, Type.MEDIUM))
            alltanks.Add(New Tank("M4A3E8 Sherman", 6, Type.MEDIUM))
            alltanks.Add(New Tank("M4A3E2", 6, Type.MEDIUM))
            alltanks.Add(New Tank("T20", 7, Type.MEDIUM))
            alltanks.Add(New Tank("M26 Pershing", 8, Type.MEDIUM))
            alltanks.Add(New Tank("M46 Patton", 9, Type.MEDIUM))
            alltanks.Add(New Tank("T14", 5, Type.HEAVY))
            alltanks.Add(New Tank("T1 heavy", 5, Type.HEAVY))
            alltanks.Add(New Tank("M6", 6, Type.HEAVY))
            alltanks.Add(New Tank("T29", 7, Type.HEAVY))
            alltanks.Add(New Tank("T34", 8, Type.HEAVY))
            alltanks.Add(New Tank("T32", 8, Type.HEAVY))
            alltanks.Add(New Tank("M6A2E1", 8, Type.HEAVY))
            alltanks.Add(New Tank("M103", 9, Type.HEAVY))
            alltanks.Add(New Tank("T110E5", 10, Type.HEAVY))
            alltanks.Add(New Tank("T18", 2, Type.TD))
            alltanks.Add(New Tank("T82", 3, Type.TD))
            alltanks.Add(New Tank("T40", 4, Type.TD))
            alltanks.Add(New Tank("M8A1", 4, Type.TD))
            alltanks.Add(New Tank("M10 Wolverine", 5, Type.TD))
            alltanks.Add(New Tank("T49", 5, Type.TD))
            alltanks.Add(New Tank("M36 Slugger", 6, Type.TD))
            alltanks.Add(New Tank("M18 Hellcat", 6, Type.TD))
            alltanks.Add(New Tank("T25 AT", 7, Type.TD))
            alltanks.Add(New Tank("T25/2", 7, Type.TD))
            alltanks.Add(New Tank("T28", 8, Type.TD))
            alltanks.Add(New Tank("T28 Prototype", 8, Type.TD))
            alltanks.Add(New Tank("T30", 9, Type.TD))
            alltanks.Add(New Tank("T95", 9, Type.TD))
            alltanks.Add(New Tank("T57", 2, Type.SPG))
            alltanks.Add(New Tank("M37", 3, Type.SPG))
            alltanks.Add(New Tank("M7 Priest", 4, Type.SPG))
            alltanks.Add(New Tank("M41", 5, Type.SPG))
            alltanks.Add(New Tank("M12", 6, Type.SPG))
            alltanks.Add(New Tank("M40/M43", 7, Type.SPG))
            alltanks.Add(New Tank("T92", 8, Type.SPG))
            ' /American
            ' French
            alltanks.Add(New Tank("RenaultFT", 1, Type.LIGHT))
            alltanks.Add(New Tank("Hotchkiss H35", 2, Type.LIGHT))
            alltanks.Add(New Tank("D1", 2, Type.LIGHT))
            alltanks.Add(New Tank("AMX 38", 3, Type.LIGHT))
            alltanks.Add(New Tank("AMX 40", 4, Type.LIGHT))
            alltanks.Add(New Tank("AMX 12t", 5, Type.LIGHT))
            alltanks.Add(New Tank("AMX 13 75", 6, Type.LIGHT))
            alltanks.Add(New Tank("AMX 13 90", 7, Type.LIGHT))
            alltanks.Add(New Tank("D2", 3, Type.MEDIUM))
            alltanks.Add(New Tank("Lorraine 40 t", 8, Type.MEDIUM))
            alltanks.Add(New Tank("Bat Chatillon 25 t", 9, Type.MEDIUM))
            alltanks.Add(New Tank("B1", 4, Type.HEAVY))
            alltanks.Add(New Tank("BDR G1B", 5, Type.HEAVY))
            alltanks.Add(New Tank("ARL 44", 6, Type.HEAVY))
            alltanks.Add(New Tank("AMX M4(1945)", 7, Type.HEAVY))
            alltanks.Add(New Tank("AMX 50 100", 8, Type.HEAVY))
            alltanks.Add(New Tank("AMX 50 120", 9, Type.HEAVY))
            alltanks.Add(New Tank("AMX 50B", 10, Type.HEAVY))
            alltanks.Add(New Tank("FCM36 Pak40", 3, Type.TD))
            alltanks.Add(New Tank("105 leFH18B2", 4, Type.SPG))
            ' /French
            ' Chinese ;)
            alltanks.Add(New Tank("Type 59", 8, Type.MEDIUM))
        End If
        Return alltanks
    End Function

End Class
